(()=>{
const d=document,$=id=>d.getElementById(id);
let tries=0,timer=0,lastQuestion='';
const norm=s=>String(s??'').toLowerCase().replace(/[’‘]/g,"'").replace(/[^a-z0-9%]+/g,' ').trim().replace(/\s+/g,' ');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const STOP=new Set('a an the is are was were be been being to of on in at by for from with and or but so this that these those it its they them their there as which who whom what when where how why explain describe state identify name suggest predict give use using does do did can could would should may might will shall'.split(' '));
const F={
 f1:{code:'F1',name:'Change → Effect',build:'Change → affected process/function → result',short:'Show how a changed condition affects a process and leads to the result.'},
 f2:{code:'F2',name:'Mechanism / Process',build:'Start → mechanism → next effect → outcome',short:'Explain the Science process in a logical sequence.'},
 f3:{code:'F3',name:'Evidence / Data → Explanation',build:'Evidence → Science concept → conclusion',short:'Use the actual result/observation, then explain what it shows.'},
 f4:{code:'F4',name:'Comparison → Explanation',build:'Relevant difference → Science reason → comparative result',short:'Compare the relevant feature first, then link it to the different result.'},
 f5:{code:'F5',name:'Structure / Feature → Function',build:'Feature → what it enables → function/advantage',short:'Link a structure or feature to what it allows the organism/object to do.'},
 f6:{code:'F6',name:'Experimental / Process-skill Explanation',build:'Setup/procedure → why it matters → quality/result',short:'Apply fair-test, variable, reliability, accuracy or conclusion rules to the exact setup.'},
 direct:{code:'Direct',name:'Direct-answer question',build:'Answer exactly what is asked',short:'No six-framework chain is needed unless the wording separately asks for explanation.'}
};
function questionType(q){const t=String(q||'').trim();if(!t)return'Question';if(/\b(explain|why|give\s+(?:a\s+)?reason)\b/i.test(t))return'Explain / Why';if(/^\s*how\b|\bdescribe how\b/i.test(t))return'How';if(/\bcompare\b/i.test(t))return'Compare';if(/^\s*describe\b/i.test(t))return'Describe';if(/^\s*suggest\b/i.test(t))return'Suggest';if(/^\s*predict\b/i.test(t))return'Predict';if(/^\s*state\b/i.test(t))return'State';if(/^\s*identify\b/i.test(t))return'Identify';if(/^\s*name\b/i.test(t))return'Name';if(/^\s*what\b/i.test(t))return'What';if(/\brelationship\b/i.test(t))return'Relationship';if(/\bconclusion\b|\bwhat can .* conclude\b/i.test(t))return'Conclusion';if(/\baim\b|\bfind out\b/i.test(t))return'Experiment aim';return'Application';}
function classify(q,opt={}){
 const raw=String(q||''),t=norm(raw),reason=/\b(explain|why|give a reason|give reason)\b/.test(t),process=!!opt.process;
 if(process||/\b(reliab|accurac|fair test|controlled variable|control variable|changed variable|measured variable|relationship|aim of the experiment|conclusion|investigat|experiment)\b/.test(t))return F.f6;
 if(/\b(results?|data|evidence|graph|table|reading|observed|observation|shows that|showed that)\b/.test(t))return F.f3;
 if(/\b(compare|compared|difference|different from|than|whereas|while)\b/.test(t))return F.f4;
 if(/\b(structure|feature|function|adaptation|advantage|shape|thick|thin|sharp|broad|wide|narrow|hollow|hairy|spines?|thorns?)\b/.test(t)&&/\b(help|helps|allow|allows|enable|enables|support|supports|protect|protects|absorb|absorbs|anchor|anchors|hold|holds|reduce|reduces|prevent|prevents)\b/.test(t))return F.f5;
 if(/^how\b/.test(t)||/\b(describe how|process|cycle|pathway|moves through|passes through|circulat|digest|photosynth|respirat|pollinat|fertilis|evaporat|condens|germinat|electromagnet|electric current|water cycle)\b/.test(t))return F.f2;
 if(reason||/\b(affect|effect|cause|causes|reduce|reduces|increase|increases|decrease|decreases|block|blocks|damage|damaged|remove|removed|add|added|heat|heated|cool|cooled|more|less|fewer)\b/.test(t))return F.f1;
 if(/^\s*(what|which|identify|name|state)\b/i.test(raw)&&!reason)return F.direct;
 if(/\bhow does .* (help|allow|enable|support|protect|anchor|hold)\b/i.test(raw))return F.f5;
 return F.direct;
}
function currentQuestion(){return String(d.querySelector('#gfBody .gf-prompt')?.textContent||'').trim()}
function processMode(){return $('guidedFlow')?.dataset?.processMode==='1'||String($('guidedFlow')?.dataset?.stage||'').startsWith('process-')}
function currentFramework(){return classify(currentQuestion(),{process:processMode()})}
function answerSignals(fr,q,a){
 const t=norm(a),qt=norm(q),parts=String(a||'').split(/[.;!?]+/).filter(x=>x.trim()).length;
 const causal=/\b(because|since|so|therefore|hence|thus|caus|lead|leading|result|reduce|increase|decrease|allow|enable|prevent|block)\b/.test(t);
 const sequence=/\b(first|then|next|after|before|when|as|through|into|from|to|finally|eventually|caus|leading)\b/.test(t);
 const evidence=/\b(results?|data|evidence|shows?|observed|observation|reading|higher|lower|more|less|greater|fewer|same|different)\b/.test(t)||/\d/.test(a);
 const compare=/\b(than|more|less|greater|lower|higher|same|different|whereas|while|both|compared)\b/.test(t);
 const functionLink=/\b(allow|allows|enable|enables|help|helps|support|supports|protect|protects|absorb|absorbs|anchor|anchors|hold|holds|prevent|prevents|so that|which helps)\b/.test(t);
 const proc=/\b(repeat|average|same|constant|fair|accurate|accuracy|reliable|reliability|apparatus|measure|measured|changed variable|measured variable|increase|decrease|remains the same|actual value)\b/.test(t);
 const qWords=norm(q).split(' ').filter(w=>w.length>3&&!STOP.has(w));const aSet=new Set(t.split(' '));const overlap=qWords.filter(w=>aSet.has(w)).length;
 if(fr===F.direct)return{level:'direct',good:true,msg:'Direct answer — no six-framework chain is required.'};
 if(fr===F.f1){const good=(causal||parts>=2)&&overlap>=1;return{good,msg:good?'Change and result are linked.':'Make the chain explicit: changed condition → affected process/function → result.'}}
 if(fr===F.f2){const good=(sequence&&parts>=2)||(sequence&&causal);return{good,msg:good?'The mechanism is written as a process chain.':'Show the process in steps: start → mechanism → next effect → outcome.'}}
 if(fr===F.f3){const good=evidence&&(causal||/\btherefore|thus|shows?\b/.test(t));return{good,msg:good?'Evidence is linked to a Science conclusion.':'Quote the actual evidence/result first, then explain what it shows.'}}
 if(fr===F.f4){const good=compare&&(causal||functionLink||parts>=2);return{good,msg:good?'A relevant comparison is linked to the result.':'State the relevant difference using more/less/same/different, then explain the different result.'}}
 if(fr===F.f5){const good=functionLink&&overlap>=1;return{good,msg:good?'The feature is linked to its function/advantage.':'Link the feature to what it allows/enables, then to the function or advantage.'}}
 if(fr===F.f6){let good=proc;if(/reliab/.test(qt))good=/repeat/.test(t);if(/accurac/.test(qt))good=/apparatus|procedure|actual value|closer|precis/.test(t);if(/fair test|kept the same|keep .* same/.test(qt))good=/same|constant|only|affect/.test(t);if(/relationship/.test(qt))good=/increase|decrease|same|remain/.test(t);return{good,msg:good?'The process-skill rule is applied to the setup.':'Apply the exact process-skill rule to this setup; name the relevant variables/procedure where needed.'}}
 return{good:true,msg:'Approach looks suitable.'};
}
function markStatus(){const b=$('gfAppFeedback');if(!b)return'';const txt=norm(b.textContent);if(!txt)return'';if(/excellent|psle acceptable|correct|cycle complete|review complete/.test(txt))return'correct';if(/not correct|needs work|concept not known|missing|wrong|repair/.test(txt))return'needs';return''}
function coachHtml(fr,q){return `<div class="fc-head"><span>🧠 Framework Coach</span><span class="fc-type">${esc(questionType(q))}</span></div><div class="fc-best"><b>${fr.code==='Direct'?'Direct answer':fr.code+' — '+fr.name}</b></div><div class="fc-build">${esc(fr.build)}</div><div class="fc-why">${esc(fr.short)}</div><div id="fcCheck" class="fc-check"></div>`}
function installStyle(){if($('frameworkCoachStyle'))return;const s=d.createElement('style');s.id='frameworkCoachStyle';s.textContent=`
.fc-card{margin:12px 0 14px;border:2px solid #c7d2fe;background:#eef2ff;border-radius:16px;padding:12px 14px;color:#312e81;line-height:1.4}.fc-head{display:flex;justify-content:space-between;gap:8px;align-items:center;font-weight:900}.fc-type{font-size:10px;background:#fff;border:1px solid #c7d2fe;border-radius:999px;padding:4px 7px;color:#475569}.fc-best{margin-top:7px;font-size:15px}.fc-build{margin-top:4px;font-weight:900;color:#1e293b}.fc-why{margin-top:4px;font-size:12px;color:#475569}.fc-check{margin-top:8px;padding-top:8px;border-top:1px solid #c7d2fe;font-size:12px;font-weight:800}.fc-check:empty{display:none}.fc-ok{color:#047857}.fc-warn{color:#b45309}.fc-direct{color:#475569}.fc-tag{display:inline-block;margin-left:5px;padding:2px 5px;border-radius:999px;background:#eef2ff;color:#4338ca;font-size:8px;font-style:normal;font-weight:900;vertical-align:1px}.fc-map{margin-top:7px;padding:8px 9px;border-radius:10px;background:#f8fafc;color:#475569;font-size:9px;line-height:1.45}.fc-filter{width:100%;margin-top:6px;border:1px solid #dbe3ee;border-radius:9px;padding:7px 8px;background:#fff;color:#475569;font-size:10px;font-weight:800}
@media(max-width:700px){.fc-card{padding:11px 12px}.fc-best{font-size:14px}.fc-build{font-size:13px}.fc-why,.fc-check{font-size:11px}}
`;d.head.appendChild(s)}
function renderCoach(){const ta=$('gfAppAnswer'),q=currentQuestion();if(!ta||!q)return;const fr=currentFramework();let card=$('frameworkCoach');if(!card){card=d.createElement('div');card.id='frameworkCoach';card.className='fc-card';ta.insertAdjacentElement('beforebegin',card)}if(card.dataset.q!==q||card.dataset.fr!==fr.code){card.dataset.q=q;card.dataset.fr=fr.code;card.innerHTML=coachHtml(fr,q)}const a=String(ta.value||'').trim(),status=markStatus(),check=$('fcCheck');if(!check)return;if(!a){check.innerHTML='<span class="fc-direct">Before writing: use the framework chain above only if the question needs it.</span>';return}if(!status){check.innerHTML='<span class="fc-direct">After you check your answer, I will also check whether your reasoning follows this approach.</span>';return}const sig=answerSignals(fr,q,a);if(fr===F.direct){check.innerHTML='<span class="fc-direct">✓ Direct-answer approach: no six-framework chain needed.</span>';return}if(sig.good&&status==='correct')check.innerHTML=`<span class="fc-ok">✅ Right approach — ${esc(fr.code)} pattern is clear, and the Science answer was accepted.</span>`;else if(sig.good)check.innerHTML=`<span class="fc-ok">✅ Right framework shape.</span> ${esc(sig.msg)} <span class="fc-warn">Repair the Science point highlighted below.</span>`;else if(status==='correct')check.innerHTML=`<span class="fc-warn">🟠 Science accepted, but make the ${esc(fr.code)} reasoning chain more explicit.</span> ${esc(sig.msg)}`;else check.innerHTML=`<span class="fc-warn">🟠 Approach needs strengthening.</span> ${esc(sig.msg)}`;
}
function baseFrameworkForRow(row){const kind=row?.dataset?.kind;if(kind==='process')return F.f6;const idx=Number(row?.dataset?.id);try{const e=Array.isArray(BANK)?BANK[idx]:null;return classify(e?.applicationQuestion||e?.phrasePrompt||'',{process:false})}catch(_e){return F.direct}}
function annotateSidebar(){const list=$('gpsList');if(!list)return;list.querySelectorAll('.gps-row').forEach(row=>{const fr=baseFrameworkForRow(row);row.dataset.framework=fr.code;const b=row.querySelector('b');if(b&&!b.querySelector('.fc-tag'))b.insertAdjacentHTML('beforeend',`<em class="fc-tag">${esc(fr.code)}</em>`)});applyFrameworkFilter();}
function frameworkCounts(){const c={F1:0,F2:0,F3:0,F4:0,F5:0,F6:12,Direct:0};try{if(Array.isArray(BANK))BANK.forEach(e=>{const x=classify(e?.applicationQuestion||e?.phrasePrompt||'').code;c[x]=(c[x]||0)+1})}catch(_e){}return c}
function installSidebarMap(){const side=$('guidedProgressSidebar');if(!side)return;const foot=side.querySelector('.gps-foot');if(foot&&!$('fcMap')){const c=frameworkCounts(),m=d.createElement('div');m.id='fcMap';m.className='fc-map';m.innerHTML=`<b>6-framework map (default question)</b><br>F1 Change→Effect ${c.F1} · F2 Mechanism/Process ${c.F2} · F3 Evidence/Data ${c.F3}<br>F4 Comparison ${c.F4} · F5 Structure→Function ${c.F5} · F6 Experiment/Process ${c.F6} · Direct ${c.Direct}<br><small>The coach reclassifies the exact Application question shown during review.</small>`;foot.appendChild(m)}const tools=side.querySelector('.gps-tools');if(tools&&!$('fcFrameworkFilter')){const c=frameworkCounts(),sel=d.createElement('select');sel.id='fcFrameworkFilter';sel.className='fc-filter';sel.innerHTML=`<option value="all">All approaches — 192</option><option value="F1">F1 Change → Effect — ${c.F1}</option><option value="F2">F2 Mechanism / Process — ${c.F2}</option><option value="F3">F3 Evidence / Data — ${c.F3}</option><option value="F4">F4 Comparison — ${c.F4}</option><option value="F5">F5 Structure / Function — ${c.F5}</option><option value="F6">F6 Experiment / Process — ${c.F6}</option><option value="Direct">Direct answer — ${c.Direct}</option>`;sel.onchange=applyFrameworkFilter;tools.appendChild(sel)}}
function applyFrameworkFilter(){const sel=$('fcFrameworkFilter'),list=$('gpsList');if(!sel||!list)return;const v=sel.value;list.querySelectorAll('.gps-row').forEach(r=>{r.style.display=(v==='all'||r.dataset.framework===v)?'':'none'});const groups=[...list.querySelectorAll('.gps-group')];groups.forEach(g=>{let n=g.nextElementSibling,any=false;while(n&&!n.classList.contains('gps-group')){if(n.classList.contains('gps-row')&&n.style.display!=='none'){any=true;break}n=n.nextElementSibling}g.style.display=any?'':'none'});const first=$('gpsOpenFirst');if(first)first.style.display=v==='all'?'':'none'}
function schedule(){clearTimeout(timer);timer=setTimeout(()=>{installSidebarMap();annotateSidebar();renderCoach()},60)}
function boot(){tries++;const flow=$('guidedFlow');if(!flow){if(tries<240)setTimeout(boot,80);return}installStyle();installSidebarMap();annotateSidebar();renderCoach();new MutationObserver(schedule).observe(flow,{childList:true,subtree:true,characterData:true,attributes:true,attributeFilter:['data-stage','data-process-mode','data-process-skill','class']});setInterval(()=>{const q=currentQuestion();if(q!==lastQuestion){lastQuestion=q;renderCoach()}annotateSidebar()},900);window.PSLE_FRAMEWORK_COACH={classify,frameworks:F,current:currentFramework,questionType};}
boot();
})();