(()=>{
const d=document,$=id=>d.getElementById(id),ENDPOINT='https://primary-science-ai-marker.limkimsze-maker.workers.dev/mark';
let tries=0,timer=0;
const norm=s=>String(s??'').toLowerCase().replace(/[’‘]/g,"'").replace(/[^a-z0-9]+/g,' ').trim().replace(/\s+/g,' ');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function visibleConceptId(){const pills=[...d.querySelectorAll('#gfBody .gf-pill')];for(const p of pills){const m=String(p.textContent||'').trim().match(/^#(\d+)$/);if(m)return Number(m[1])}return 0}
function idx(){const id=visibleConceptId();try{if(id&&Array.isArray(BANK)){const j=BANK.findIndex(e=>Number(e?.id)===id);if(j>=0)return j}return typeof current==='function'?current():-1}catch(_e){return -1}}
function visibleKnown(){return [...d.querySelectorAll('#gfBody .gf-pill')].some(p=>/known/i.test(String(p.textContent||''))&&(/✅/.test(String(p.textContent||''))||p.classList.contains('done')))}
function known(){try{const i=idx();return visibleKnown()||(i>=0&&new Set(rec(i)?.appCorrectDates||[]).size>=1)}catch(_e){return visibleKnown()}}
function scienceApplication(){return !!visibleConceptId()&&!!$('gfAppAnswer')&&!!d.querySelector('#gfBody .gf-prompt')}
function q(){return String(d.querySelector('#gfBody .gf-prompt')?.textContent||'').trim()}
function qkey(x){return norm(x).slice(0,220)}
function entry(){const i=idx();try{return i>=0?BANK[i]:null}catch(_e){return null}}
function record(){const i=idx();try{return i>=0?rec(i):null}catch(_e){return null}}
function savedAnswer(question){const r=record(),k=qkey(question);return String(r?.guidedShownAnswerByQuestion?.[k]||r?.guidedImprovedByQuestion?.[k]||'').trim()}
function remember(question,answer){if(!question||!answer)return;try{const r=record(),k=qkey(question);if(!r||!k)return;r.guidedShownAnswerByQuestion=r.guidedShownAnswerByQuestion||{};r.guidedShownAnswerByQuestion[k]=answer;const keys=Object.keys(r.guidedShownAnswerByQuestion);if(keys.length>30)keys.slice(0,keys.length-30).forEach(x=>delete r.guidedShownAnswerByQuestion[x]);save()}catch(_e){}}
function installStyle(){if($('knownAnswerStyle'))return;const s=d.createElement('style');s.id='knownAnswerStyle';s.textContent=`
.ka-controls{margin:14px 0 12px;display:flex;justify-content:center}.ka-controls button{width:min(100%,520px);background:#ecfdf5!important;color:#047857!important;border:2px solid #34d399!important;box-shadow:0 5px 16px #05966914}.ka-controls button:hover{background:#d1fae5!important}.ka-box{margin:0 0 14px;padding:15px 16px;border-radius:15px;border:2px solid #86efac;background:#ecfdf5;color:#14532d;line-height:1.6}.ka-box b{display:block;margin-bottom:6px}.ka-box .ka-answer{font-size:16px;font-weight:800}.ka-box small{display:block;margin-top:9px;color:#475569;font-weight:700}.ka-loading{color:#475569;background:#f8fafc;border-color:#cbd5e1}.ka-note{font-size:11px;color:#047857;font-weight:900;margin-top:5px;text-align:center}
`;d.head.appendChild(s)}
function payload(question,e,seed){return{conceptId:Number(e?.id||idx()+1),topic:e?.topic||'',question,answer:seed,verbatim:e?.phrase||'',modelAnswer:e?.modelApplicationAnswer||e?.phrase||'',rubric:Array.isArray(e?.rubric)?e.rubric:[]}}
async function generate(question,e){const core=String(e?.modelApplicationAnswer||e?.phrase||'').trim();if(!core)return'';if(norm(question)===norm(e?.phrasePrompt||''))return core;const ctl=new AbortController(),to=setTimeout(()=>ctl.abort(),25000);try{const res=await fetch(ENDPOINT,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload(question,e,core)),signal:ctl.signal});const raw=await res.text();let data={};try{data=JSON.parse(raw)}catch(_e){}if(!res.ok)throw new Error('AI answer guide unavailable');return String(data?.improvedAnswer||'').trim()||core}finally{clearTimeout(to)}}
async function toggle(){const btn=$('gfShowKnownAnswer'),box=$('gfKnownAnswerBox'),question=q(),e=entry();if(!btn||!box||!question||!e)return;if(!box.hidden){box.hidden=true;btn.textContent='👁 Show answer — Known review';btn.setAttribute('aria-expanded','false');return}box.hidden=false;btn.textContent='🙈 Hide answer';btn.setAttribute('aria-expanded','true');let ans=savedAnswer(question);if(ans){box.className='ka-box';box.innerHTML=`<b>Suggested PSLE answer</b><div class="ka-answer">${esc(ans)}</div><small>Review only. Scientifically equivalent wording may also be correct. Showing this answer does not change Known progress.</small>`;return}box.className='ka-box ka-loading';box.innerHTML='<b>Preparing a question-specific answer…</b><small>Using the exact Application question and the book-backed Science concept.</small>';btn.disabled=true;try{ans=await generate(question,e);if(ans){remember(question,ans);box.className='ka-box';box.innerHTML=`<b>Suggested PSLE answer</b><div class="ka-answer">${esc(ans)}</div><small>Review only. Scientifically equivalent wording may also be correct. Showing this answer does not change Known progress.</small>`}else box.innerHTML='<b>Answer guide unavailable.</b><small>Use the Flashcard Science concept and the question framework.</small>'}catch(_e){const core=String(e?.modelApplicationAnswer||e?.phrase||'').trim();box.className='ka-box';box.innerHTML=core?`<b>Book-backed Science core</b><div class="ka-answer">${esc(core)}</div><small>Adapt this core to the exact question. The question-specific answer could not be prepared just now.</small>`:'<b>Answer guide unavailable.</b>'}finally{btn.disabled=false}}
function remove(){d.querySelector('.ka-controls')?.remove();$('gfKnownAnswerBox')?.remove()}
function render(){const body=$('gfBody'),ta=$('gfAppAnswer'),question=q();if(!body||!ta||!question||!scienceApplication()||!known()){remove();return}const sig=qkey(question);let wrap=d.querySelector('.ka-controls'),btn=$('gfShowKnownAnswer'),box=$('gfKnownAnswerBox');if(btn&&btn.dataset.q!==sig){remove();wrap=btn=box=null}if(!btn){wrap=d.createElement('div');wrap.className='ka-controls';btn=d.createElement('button');btn.id='gfShowKnownAnswer';btn.type='button';btn.className='gf-btn';btn.dataset.q=sig;btn.textContent='👁 Show answer — Known review';btn.setAttribute('aria-expanded','false');btn.setAttribute('aria-controls','gfKnownAnswerBox');wrap.appendChild(btn);box=d.createElement('div');box.id='gfKnownAnswerBox';box.hidden=true;ta.insertAdjacentElement('beforebegin',wrap);wrap.insertAdjacentElement('afterend',box);btn.onclick=toggle}}
function schedule(){clearTimeout(timer);timer=setTimeout(render,40)}
function boot(){tries++;const f=$('guidedFlow');if(!f){if(tries<240)setTimeout(boot,80);return}installStyle();new MutationObserver(schedule).observe(f,{childList:true,subtree:true,characterData:true,attributes:true,attributeFilter:['data-stage','class']});render();setInterval(render,700)}
boot();
})();