(()=>{
let tries=0,lastKnown=-1,sessionGain=0,lastStage='',lastFeedback='';
const $=id=>document.getElementById(id);
const reduced=()=>window.matchMedia?.('(prefers-reduced-motion: reduce)')?.matches;
function api(){return window.PSLE_PROCESS_MERGE||null}
function scienceKnown(){let n=0;try{for(let i=0;i<BANK.length;i++)if(new Set(rec(i)?.appCorrectDates||[]).size>=1)n++}catch(_e){}return n}
function processKnown(){let n=0;try{for(const s of (api()?.skills?.()||[]))if(api()?.isKnown?.(s.id))n++}catch(_e){}return n}
function totalKnown(){return scienceKnown()+processKnown()}
const milestones=[1,5,10,25,50,75,100,125,150,175,192];
function nextMilestone(k){return milestones.find(x=>x>k)||192}
function titleFor(k){if(k>=192)return 'Mastery Complete';if(k>=150)return 'PSLE Science Ace';if(k>=100)return 'Science Strategist';if(k>=60)return 'Science Specialist';if(k>=30)return 'Scientist';if(k>=15)return 'Investigator';if(k>=5)return 'Explorer';return 'Starter'}
function stageName(){const f=$('guidedFlow');if(!f)return 'flash';if(f.dataset.processMode==='1'){const s=String(f.dataset.stage||'process-flash');return s.replace('process-','')}return f.dataset.stage||'flash'}
function coachLine(){const st=stageName(),mode=String(document.querySelector('.gf-ladder .active')?.textContent||'').toLowerCase(),bad=String(document.querySelector('#gfMemFeedback .bad,#gfAppFeedback .bad')?.textContent||'');if(bad){if(/missing|change|extra|not exact/i.test(bad))return 'Good attempt. Repair only the words that changed, then try again.';return 'Use the feedback as a clue. Fix one scoring idea at a time.'}if(st==='flash')return 'Flip as many times as you need. Confidence first; speed can come later.';if(st==='mem'){if(mode.includes('fill'))return 'The clue is support, not a setback. Rebuild the sentence from the parts you know.';if(mode.includes('learn'))return 'Study the exact wording once, copy it carefully, then move on.';return 'Try to retrieve the whole idea before looking back. That effort strengthens memory.'}if(st==='app')return 'Transfer time: read the command word first, then use the Science idea in this new context.';return 'One focused step at a time.'}
function install(){const flow=$('guidedFlow');if(!flow||$('motivationBar'))return;const bar=document.createElement('section');bar.id='motivationBar';bar.innerHTML=`<div class="mv-top"><div><div class="mv-label">MASTERY MISSION</div><div class="mv-title"><span id="mvLevel"></span><span id="mvXp"></span></div></div><div class="mv-quest"><b id="mvQuest"></b><small>session quest</small></div></div><div class="mv-track"><span id="mvTrack"></span></div><div class="mv-row"><span id="mvProgress"></span><span id="mvNext"></span></div><div id="mvCoach" class="mv-coach"></div>`;const top=flow.querySelector('.gf-top');top?.insertAdjacentElement('afterend',bar);const toast=document.createElement('div');toast.id='mvToast';toast.setAttribute('aria-live','polite');document.body.appendChild(toast);const style=document.createElement('style');style.id='motivationStyle';style.textContent=`
#motivationBar{margin:0 0 12px;padding:13px 15px;border:1px solid #dbeafe;border-radius:17px;background:linear-gradient(135deg,#eef2ff,#ecfeff);box-shadow:0 7px 22px #0f172a0b}.mv-top{display:flex;justify-content:space-between;gap:12px;align-items:center}.mv-label{font-size:10px;letter-spacing:.13em;font-weight:900;color:#4f46e5}.mv-title{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin-top:2px}.mv-title #mvLevel{font-size:18px;font-weight:900;color:#172033}.mv-title #mvXp{font-size:11px;font-weight:900;background:#fff;border:1px solid #c7d2fe;color:#4338ca;border-radius:999px;padding:4px 8px}.mv-quest{text-align:right}.mv-quest b{display:block;font-size:16px;color:#047857}.mv-quest small{display:block;color:#64748b;font-size:9px;font-weight:800}.mv-track{height:8px;border-radius:999px;background:#dbeafe;overflow:hidden;margin:10px 0 6px}.mv-track span{display:block;height:100%;width:0;border-radius:inherit;background:linear-gradient(90deg,#4f46e5,#0f766e);transition:width .45s ease}.mv-row{display:flex;justify-content:space-between;gap:10px;color:#64748b;font-size:10px;font-weight:800}.mv-coach{margin-top:9px;border-top:1px solid #dbeafe;padding-top:9px;color:#334155;font-size:12px;font-weight:800;line-height:1.45}.mv-coach::before{content:'💡 ';}.mv-pop{animation:mvpop .45s ease}.mv-glow{animation:mvglow .9s ease}@keyframes mvpop{0%{transform:scale(.97)}55%{transform:scale(1.025)}100%{transform:scale(1)}}@keyframes mvglow{0%,100%{box-shadow:0 7px 22px #0f172a0b}50%{box-shadow:0 0 0 5px #a7f3d055,0 14px 32px #0f172a14}}#mvToast{position:fixed;left:50%;bottom:24px;transform:translate(-50%,18px);z-index:999999;opacity:0;pointer-events:none;background:#172033;color:#fff;border-radius:15px;padding:12px 16px;box-shadow:0 16px 44px #0004;font:800 13px Arial;text-align:center;max-width:min(430px,calc(100vw - 30px));transition:.24s ease}#mvToast.show{opacity:1;transform:translate(-50%,0)}.mv-confetti{position:fixed;z-index:999998;width:8px;height:12px;border-radius:2px;top:10%;pointer-events:none;animation:mvfall 1.15s ease-out forwards}@keyframes mvfall{to{transform:translate(var(--dx),78vh) rotate(520deg);opacity:0}}@media(max-width:600px){.mv-row{flex-direction:column;gap:2px}.mv-quest b{font-size:14px}}@media(prefers-reduced-motion:reduce){.mv-track span,#mvToast{transition:none}.mv-pop,.mv-glow{animation:none!important}.mv-confetti{display:none!important}}
`;document.head.appendChild(style);lastKnown=totalKnown();render();new MutationObserver(schedule).observe(flow,{subtree:true,childList:true,attributes:true,attributeFilter:['data-stage','data-process-mode','data-process-skill']});document.addEventListener('psle-process-progress',schedule);document.addEventListener('psle-process-mode',schedule)}
let timer=0;function schedule(){clearTimeout(timer);timer=setTimeout(render,45)}
function render(){const bar=$('motivationBar');if(!bar)return;const k=totalKnown();if(lastKnown<0)lastKnown=k;if(k>lastKnown){const gained=k-lastKnown;sessionGain+=gained;celebrate(k,gained)}lastKnown=k;const pct=Math.max(0,Math.min(100,k/192*100));$('mvLevel').textContent=titleFor(k);$('mvXp').textContent=`${k*100} Mastery XP`;$('mvTrack').style.width=pct+'%';$('mvProgress').textContent=`${k}/192 Known · ${192-k} to go`;const next=nextMilestone(k);$('mvNext').textContent=k>=192?'All 192 mastered ✓':`${next-k} to next milestone (${next})`;$('mvQuest').textContent=`${Math.min(sessionGain,3)}/3 mastered`;$('mvCoach').textContent=coachLine();const st=stageName(),feedback=String(document.querySelector('#gfMemFeedback,#gfAppFeedback')?.textContent||'').trim();if(st!==lastStage){bar.classList.remove('mv-pop');void bar.offsetWidth;bar.classList.add('mv-pop');lastStage=st}if(feedback&&feedback!==lastFeedback){lastFeedback=feedback;if(/memorisation complete|exact recall.*complete/i.test(feedback))toast('Memory locked in ✓\nNow use it in Application.');else if(/not exact|missing|needs work|not correct/i.test(feedback))toast('Useful feedback found. Repair it and try again.')}if(sessionGain>=3&&!bar.dataset.questDone){bar.dataset.questDone='1';toast('Session quest complete 🎯\n3 items mastered this sitting.')}}
function toast(text){const t=$('mvToast');if(!t)return;t.innerHTML=String(text).replace(/\n/g,'<br>');t.classList.add('show');clearTimeout(t._hide);t._hide=setTimeout(()=>t.classList.remove('show'),2600)}
function celebrate(k,gained){const bar=$('motivationBar');bar?.classList.remove('mv-glow');if(bar){void bar.offsetWidth;bar.classList.add('mv-glow')}const crossed=milestones.filter(m=>m<=k&&m>k-gained).pop();toast(crossed?`🏅 Milestone unlocked: ${crossed} Known!\nKeep turning knowledge into application.`:`✅ Item mastered! +${gained*100} Mastery XP`);if(!reduced())confetti(crossed?30:18)}
function confetti(n){const chars=['#4f46e5','#0f766e','#f59e0b','#ec4899','#22c55e'];for(let i=0;i<n;i++){const c=document.createElement('i');c.className='mv-confetti';c.style.left=(15+Math.random()*70)+'vw';c.style.background=chars[i%chars.length];c.style.setProperty('--dx',((Math.random()-.5)*240)+'px');c.style.animationDelay=(Math.random()*.18)+'s';document.body.appendChild(c);setTimeout(()=>c.remove(),1500)}}
function boot(){tries++;if(!$('guidedFlow')||typeof BANK==='undefined'||typeof rec!=='function'||!api()){if(tries<220)setTimeout(boot,80);return}install()}
boot();
})();