window.PROCESS_SKILLS=[
{id:1,topic:'Fair test',cue:'What makes an experiment a fair test?',target:'A fair test changes only one variable while all other relevant variables are kept constant.',source:'Revision book pp. 90–93',focus:true,variants:[
{q:'A pupil investigates whether the amount of light affects plant growth. Why must the type of plant be kept the same?',model:'The type of plant must be kept the same so that only the amount of light affects the plant growth.'},
{q:'Two identical toy cars are tested on different surfaces. Explain why the same car should be used for both tests.',model:'The same car should be used so that only the type of surface affects the measured result.'},
{q:'A pupil changes the temperature of water to investigate how fast sugar dissolves. Why must the amount of sugar be kept the same?',model:'The amount of sugar must be kept the same so that only the temperature of the water affects the time taken for the sugar to dissolve.'}]},
{id:2,topic:'Changed, measured and controlled variables',cue:'How do you identify the variables in an experiment?',target:'The changed variable is what the investigator changes, the measured variable is what is measured as the effect, and other relevant variables are kept the same.',source:'Revision book pp. 90–93',variants:[
{q:'A pupil changes the number of batteries and records bulb brightness. State the changed and measured variables.',model:'The changed variable is the number of batteries. The measured variable is the brightness of the bulb.'},
{q:'A pupil changes the distance between a lamp and a plant and counts bubbles per minute. State the changed and measured variables.',model:'The changed variable is the distance between the lamp and the plant. The measured variable is the number of bubbles produced per minute.'}]},
{id:3,topic:'Relationship from data',cue:'How should a relationship from data be stated?',target:'A relationship should state how the measured variable changes as the changed variable increases or decreases.',source:'Revision book pp. 90–93',variants:[
{q:'As the amount of carbon dioxide increases, the number of bubbles produced per minute also increases. State the relationship.',model:'As the amount of carbon dioxide increases, the number of bubbles produced per minute increases.'},
{q:'A graph shows that as distance from a lamp increases, the number of bubbles produced decreases. State the relationship.',model:'As the distance from the lamp increases, the number of bubbles produced per minute decreases.'}]},
{id:4,topic:'Hypothesis',cue:'What is a hypothesis?',target:'A hypothesis is a prediction of how the changed variable will affect the measured variable.',source:'Revision book pp. 90–93',variants:[
{q:'Write a hypothesis for an experiment on how water temperature affects the time taken for sugar to dissolve.',model:'As the temperature of the water increases, the time taken for the sugar to dissolve decreases.'},
{q:'Write a hypothesis for an experiment on how the number of batteries affects bulb brightness.',model:'As the number of batteries increases, the brightness of the bulb increases.'}]},
{id:5,topic:'Reliability',cue:'How can the reliability of experimental results be improved?',target:'Reliability is improved by repeating the experiment to obtain consistent results and calculating an average when appropriate.',source:'Revision book pp. 90, 92',focus:true,variants:[
{q:'A pupil carries out an experiment only once. Suggest how he can increase the reliability of his results.',model:'Repeat the experiment several times, check that the results are consistent and calculate the average result.'},
{q:'A pupil measures how far a toy car travels. What should she do to obtain more reliable results?',model:'She should repeat the experiment several times and calculate the average distance if the repeated results are consistent.'},
{q:'Why is repeating an experiment useful?',model:'Repeating the experiment allows the results to be checked for consistency and makes the result more reliable.'}]},
{id:6,topic:'Accuracy',cue:'What is the difference between accuracy and reliability?',target:'Accuracy means results are close to the actual value, while reliability means repeated results are consistent or similar.',source:'Revision book pp. 90, 92–93',variants:[
{q:'A pupil repeats an inaccurate measurement many times and gets similar readings. Are the results necessarily accurate?',model:'No. Similar repeated readings show reliability, but accuracy depends on whether the readings are close to the actual value and on using the correct apparatus and procedure.'},
{q:'How can a pupil improve the accuracy of a measurement?',model:'Use suitable precise apparatus and take the reading correctly so that the measurement is close to the actual value.'}]},
{id:7,topic:'Control set-up',cue:'What is the purpose of a control set-up?',target:'A control set-up uses the same conditions but without the changed factor so that the effect of that factor can be compared and confirmed.',source:'Revision book p. 93',variants:[
{q:'A pupil tests whether fertiliser affects plant growth. What should the control set-up be?',model:'The control set-up should be kept under the same conditions but without fertiliser so that the effect of fertiliser can be compared.'},
{q:'Why is a control set-up useful?',model:'It provides a comparison so that the effect of the changed factor can be confirmed.'}]},
{id:8,topic:'Choosing apparatus — range and precision',cue:'How should measuring apparatus be chosen?',target:'Choose apparatus according to what is measured and the required range and precision.',source:'Revision book pp. 94–98',variants:[
{q:'A pupil needs to measure a very small volume of liquid accurately. What type of apparatus should be chosen?',model:'Use a suitable small-volume measuring instrument such as a syringe or dropper with appropriate graduations.'},
{q:'Why should the range of a measuring instrument suit the measurement?',model:'A suitable range and finer scale allow the required measurement to be taken with appropriate precision.'}]},
{id:9,topic:'Measuring cylinder versus beaker',cue:'Why is a measuring cylinder preferred to a beaker for accurate liquid-volume measurements?',target:'A measuring cylinder is preferred to a beaker for accurate liquid-volume measurements because it has finer graduations and gives more precise readings.',source:'Revision book pp. 94–98',variants:[
{q:'A pupil must measure 37 mL of water accurately. Should she use a beaker or a measuring cylinder? Explain.',model:'She should use a measuring cylinder because its finer graduations allow a more precise measurement of the water volume.'},
{q:'Why is a beaker less suitable when an accurate liquid-volume reading is required?',model:'A beaker has coarser markings and is less precise than a measuring cylinder for measuring liquid volume.'}]},
{id:10,topic:'Reading liquid volume',cue:'How should a liquid-volume reading be taken?',target:'Read the liquid level at eye level where appropriate to avoid an incorrect reading due to viewing angle.',source:'Revision book pp. 94–98',variants:[
{q:'Why should a pupil place her eye at the same level as the liquid before taking a reading?',model:'Reading at eye level avoids an incorrect reading caused by viewing the scale from above or below.'},
{q:'A pupil reads a measuring cylinder from above. What should he change?',model:'He should position his eye at the same level as the liquid level before taking the reading.'}]},
{id:11,topic:'Volume by water displacement',cue:'How is the volume of an irregular solid measured using water displacement?',target:'Measure the initial water volume, submerge the object fully, measure the final water volume, then subtract the initial volume from the final volume.',source:'Revision book pp. 94–98',variants:[
{q:'The water level rises from 45 mL to 68 mL when a stone is fully submerged. What is the volume of the stone?',model:'The volume of the stone is 68 mL minus 45 mL = 23 mL, which is 23 cm³.'},
{q:'Describe how to find the volume of an irregular solid using a measuring cylinder.',model:'Record the initial water volume, fully submerge the object, record the final volume and subtract the initial reading from the final reading.'}]},
{id:12,topic:'Command words, observation and comparison',cue:'What should you do before answering a Science question?',target:'Identify the command word first and match the response to it; observations state what is seen or measured, while inferences are conclusions based on observations.',source:'Revision book p. 100',focus:true,variants:[
{q:'A question asks, “What did the pupil observe?” Should the answer give a conclusion or what was actually seen or measured?',model:'Give what was actually seen or measured. An observation should not replace the evidence with a conclusion.'},
{q:'A question says “compare A and B”. What must a complete answer do?',model:'The answer should refer to both A and B and state the relevant similarity and/or difference.'},
{q:'A question says “state”. How should the answer be written?',model:'Give a concise answer with little or no supporting argument unless the question asks for an explanation.'}]}
];