(()=>{
const d=document;
if(d.getElementById('universalDisplayStyle'))return;
const s=d.createElement('style');s.id='universalDisplayStyle';s.textContent=`
html{box-sizing:border-box;-webkit-text-size-adjust:100%;text-size-adjust:100%}*,*::before,*::after{box-sizing:inherit}html,body{max-width:100%;overflow-x:hidden}body{padding-left:env(safe-area-inset-left);padding-right:env(safe-area-inset-right)}button,input,select,textarea{font-family:inherit}button{touch-action:manipulation}img,svg,canvas,video{max-width:100%;height:auto}

/* Sign-in page */
.wrap{width:min(100%,1040px);padding-left:clamp(12px,2.2vw,24px);padding-right:clamp(12px,2.2vw,24px)}.profiles{align-items:stretch}.profile{min-width:0}.summary{grid-template-columns:repeat(2,minmax(0,1fr))}.metric{min-width:0}.signin,.reset,.actions button{min-height:44px}.box{max-height:min(88dvh,760px);overflow:auto}.sm-row{min-width:0}.sm-row>*{min-width:0}

/* Guided trainer - large and medium displays */
body.gf-on>.wrap{width:min(100%,1480px)!important;max-width:1480px!important;padding-left:clamp(10px,1.8vw,24px)!important;padding-right:clamp(10px,1.8vw,24px)!important}.gf-top,.mv-top,.mv-row{min-width:0}.gf-top>*,.mv-top>*,.mv-row>*{min-width:0}.gf-picker{min-width:0}.gf-picker>*{min-width:0}.gf-searchwrap input{min-width:0}.gf-card{min-width:0}.gf-prompt,.gf-answer,.gf-cue{overflow-wrap:anywhere}.gf-textarea{max-width:100%;min-height:clamp(120px,20vh,190px)}.gf-btn,.gf-picker input,.gf-picker select,.gps-tabs button,.gps-tools button,.gps-icon{min-height:42px}.gf-btn{white-space:normal}.gf-actions{align-items:stretch}.gf-guide{overflow-wrap:anywhere}#guidedLayout{width:100%;max-width:1440px!important;grid-template-columns:minmax(0,1fr) minmax(250px,310px)!important}.gps-list{overscroll-behavior:contain}.gps-row{min-width:0}.gps-row span{min-width:0}.gps-row b,.gps-row small{overflow-wrap:anywhere}

/* Keep short Chromebook/laptop screens compact without shrinking readability */
@media (min-width:901px) and (max-height:820px){
 body.gf-on>.wrap{padding-top:8px!important}.gf-top{margin-bottom:6px!important}.gf-top h2{font-size:clamp(24px,2.6vw,32px)!important}.gf-picker{padding:8px!important;margin-bottom:4px!important}.gf-picker input,.gf-picker select{padding:8px 9px!important}.gf-steps{padding:9px 13px!important;margin-bottom:9px!important}.gf-card{padding:clamp(18px,2.5vw,28px)!important;min-height:340px!important}.gf-prompt{margin:24px auto 16px!important;font-size:clamp(25px,3vw,36px)!important}.gf-answer{margin:22px auto!important;font-size:clamp(24px,2.8vw,34px)!important}#motivationBar{padding:9px 12px!important;margin-bottom:8px!important}.mv-coach{margin-top:6px!important;padding-top:6px!important}.gf-textarea{min-height:105px!important}#guidedProgressSidebar{max-height:calc(100dvh - 18px)!important;top:9px!important;margin-top:9px!important}
}

/* Tablet / narrow Chromebook */
@media (max-width:1100px){
 #guidedLayout{grid-template-columns:1fr!important;max-width:980px!important}.gf-top{padding-right:4px}#guidedProgressSidebar{position:static!important;max-height:none!important;order:2!important;margin-top:0!important}.gps-list{max-height:260px!important}.gps-collapsed{grid-template-columns:1fr!important}.gps-collapsed #guidedProgressSidebar{min-height:auto!important}.gps-collapsed .gps-head{justify-content:flex-end!important}.gf-picker{grid-template-columns:minmax(0,1.4fr) minmax(150px,.8fr)!important}.gf-searchwrap,.gf-counts{grid-column:auto!important}.gf-counts{justify-content:flex-start!important}.mv-top{align-items:flex-start}
}

/* Phones */
@media (max-width:700px){
 body{font-size:16px}.wrap{padding:14px 10px 34px}.hero{margin:8px 0 16px}.hero h1{font-size:clamp(26px,8vw,36px);line-height:1.08}.hero p{font-size:13px}.profiles{grid-template-columns:1fr!important;gap:12px}.profile{border-radius:18px;padding:16px}.avatar{width:52px;height:52px;font-size:26px;margin-bottom:8px}.profile h2{font-size:24px}.summary{gap:6px;margin:12px 0}.metric{padding:9px}.metric b{font-size:18px}.signin{font-size:16px;min-height:48px}.reset{min-height:44px}.note{font-size:12px;margin-top:12px}.sm-progress{margin:10px 0!important}.box{width:100%!important;border-radius:16px;padding:17px}.actions{display:grid;grid-template-columns:1fr}.actions button{width:100%}

 body.gf-on>.wrap{padding:8px 8px calc(18px + env(safe-area-inset-bottom))!important}.gf-top{display:grid!important;grid-template-columns:minmax(0,1fr) auto;gap:8px!important;align-items:start!important}.gf-top h2{font-size:clamp(24px,7vw,31px)!important;margin:2px 0!important}.gf-meta{font-size:12px!important}.gf-ghost{min-height:40px!important;padding:7px 9px!important}.gf-picker{grid-template-columns:1fr 1fr!important;gap:6px!important;padding:7px!important;border-radius:14px!important}.gf-searchwrap{grid-column:1/-1!important}.gf-counts{grid-column:1/-1!important;font-size:11px!important}.gf-picker input,.gf-picker select{font-size:16px!important;min-height:44px!important;padding:9px 10px!important}.gf-filter-note{font-size:10px!important;margin-bottom:5px!important}.gf-steps{padding:8px!important;border-radius:14px!important;margin-bottom:8px!important;overflow-x:auto!important;scrollbar-width:none}.gf-steps::-webkit-scrollbar{display:none}.gf-step{min-width:106px!important;grid-template-columns:28px auto!important;column-gap:7px!important}.gf-step span{width:28px!important;height:28px!important}.gf-step b{font-size:12px!important}.gf-step small{font-size:9px!important}.gf-line{min-width:18px!important;margin:0 4px!important}.gf-card{padding:15px!important;border-radius:18px!important;min-height:0!important}.gf-pillrow{margin-bottom:10px!important;gap:5px!important}.gf-pill{font-size:10px!important;padding:5px 8px!important}.gf-prompt{font-size:clamp(23px,7.2vw,32px)!important;line-height:1.25!important;margin:24px auto 16px!important}.gf-answer{font-size:clamp(22px,6.8vw,30px)!important;margin:22px auto!important}.gf-hint{font-size:13px!important;margin:12px 0!important}.gf-cue{font-size:clamp(18px,5.5vw,24px)!important;padding:14px!important;margin:12px 0!important}.gf-mode{font-size:clamp(19px,5.5vw,24px)!important}.gf-textarea{font-size:17px!important;min-height:122px!important;padding:13px!important;border-radius:14px!important}.gf-actions{display:grid!important;grid-template-columns:1fr!important;gap:7px!important;margin-top:14px!important}.gf-btn{width:100%!important;min-height:46px!important;font-size:15px!important;padding:11px 13px!important}.gf-guide{font-size:13px!important;padding:11px!important;margin:10px 0!important}.gf-guide .frame-grid{grid-template-columns:1fr!important}.gf-feedback{font-size:13px!important;padding:11px 12px!important;margin-top:11px!important}.gf-ladder{gap:5px!important;margin-bottom:12px!important}.gf-ladder div{padding:8px 5px!important;font-size:10px!important}

 #motivationBar{padding:10px 11px!important;border-radius:14px!important;margin-bottom:8px!important}.mv-top{display:grid!important;grid-template-columns:1fr auto!important;gap:7px!important}.mv-title #mvLevel{font-size:16px!important}.mv-title #mvXp{font-size:9px!important}.mv-quest b{font-size:13px!important}.mv-track{margin:7px 0 5px!important}.mv-row{display:grid!important;grid-template-columns:1fr!important;gap:1px!important;font-size:9px!important}.mv-coach{font-size:11px!important;margin-top:7px!important;padding-top:7px!important}

 #guidedLayout{display:block!important;max-width:none!important;margin:0!important}.ud-list-toggle{display:flex!important;position:fixed;right:12px;bottom:calc(12px + env(safe-area-inset-bottom));z-index:999996;min-height:46px;border:0;border-radius:999px;background:#172033;color:#fff;padding:0 15px;align-items:center;gap:7px;font:900 12px Arial;box-shadow:0 10px 28px #0004}.ud-list-toggle .ud-badge{min-width:22px;height:22px;border-radius:999px;background:#4f46e5;display:grid;place-items:center;padding:0 6px}.ud-close-list{display:block!important;margin-left:auto;border:0;background:#f1f5f9;border-radius:9px;min-width:34px;height:34px;font-size:18px;font-weight:900;color:#475569}.gps-icon{display:none!important}#guidedProgressSidebar{display:none!important;position:fixed!important;left:8px!important;right:8px!important;bottom:calc(8px + env(safe-area-inset-bottom))!important;top:auto!important;z-index:999997!important;max-height:min(72dvh,620px)!important;margin:0!important;border-radius:19px!important;box-shadow:0 24px 80px #0006!important}.ud-list-open #guidedProgressSidebar{display:flex!important}.gps-head{padding:12px!important}.gps-list{max-height:none!important;flex:1;min-height:0}.gps-tabs button,.gps-tools button{min-height:42px!important}.gps-row{padding:9px 7px!important}.gps-row b{font-size:13px!important}.gps-row small{font-size:10px!important}.gps-foot{padding-bottom:calc(10px + env(safe-area-inset-bottom))!important}
}

/* Very small phones */
@media (max-width:390px){
 .summary{grid-template-columns:1fr 1fr}.metric span{font-size:10px}.metric b{font-size:17px}.gf-picker{grid-template-columns:1fr!important}.gf-searchwrap,.gf-counts{grid-column:auto!important}.gf-top{grid-template-columns:1fr!important}.gf-ghost{justify-self:start}.gf-ladder{grid-template-columns:1fr!important}.gf-ladder div{padding:7px!important}.mv-top{grid-template-columns:1fr!important}.mv-quest{text-align:left!important}.gf-prompt{font-size:23px!important}.gf-answer{font-size:22px!important}
}

/* Short landscape phone / small laptop window */
@media (max-height:520px) and (orientation:landscape){
 body.gf-on>.wrap{padding-top:4px!important}.gf-top{margin-bottom:4px!important}.gf-top h2{font-size:22px!important}.gf-picker{padding:5px!important}.gf-steps{margin-bottom:5px!important;padding:5px!important}.gf-card{padding:12px!important}.gf-prompt{font-size:22px!important;margin:13px auto 10px!important}.gf-answer{font-size:21px!important;margin:12px auto!important}.gf-hint{margin:8px 0!important}.gf-textarea{min-height:82px!important}.gf-actions{margin-top:9px!important}.gf-btn{min-height:40px!important;padding:8px 11px!important}#motivationBar{padding:7px 10px!important}.mv-coach{display:none!important}.gf-filter-note{display:none!important}#guidedProgressSidebar{max-height:88dvh!important}
}

@media (min-width:1600px){#guidedLayout{grid-template-columns:minmax(0,1fr) 330px!important;max-width:1540px!important}.gf-card{padding-left:44px!important;padding-right:44px!important}}
@media (prefers-reduced-motion:reduce){*,*::before,*::after{scroll-behavior:auto!important;animation-duration:.001ms!important;animation-iteration-count:1!important;transition-duration:.001ms!important}}
`;
d.head.appendChild(s);

function ensureViewport(){const v=d.querySelector('meta[name="viewport"]');if(v)v.setAttribute('content','width=device-width,initial-scale=1,viewport-fit=cover');}
function installMobileList(){const side=d.getElementById('guidedProgressSidebar');if(!side||d.getElementById('udListToggle'))return;const toggle=d.createElement('button');toggle.id='udListToggle';toggle.className='ud-list-toggle';toggle.type='button';toggle.innerHTML='<span>☰ Mastery list</span><span class="ud-badge" id="udListBadge">0</span>';d.body.appendChild(toggle);const close=d.createElement('button');close.id='udCloseList';close.className='ud-close-list';close.type='button';close.setAttribute('aria-label','Close mastery list');close.textContent='×';const head=side.querySelector('.gps-head');head?.appendChild(close);const count=()=>{const b=d.getElementById('gpsNotDone'),out=d.getElementById('udListBadge');if(!out)return;const m=String(b?.textContent||'').match(/(\d+)/);out.textContent=m?m[1]:'0'};toggle.onclick=()=>{d.body.classList.toggle('ud-list-open');count()};close.onclick=()=>d.body.classList.remove('ud-list-open');side.addEventListener('click',e=>{if(e.target.closest('.gps-row'))setTimeout(()=>d.body.classList.remove('ud-list-open'),120)});new MutationObserver(count).observe(side,{subtree:true,childList:true,characterData:true});count();}
function boot(){ensureViewport();installMobileList();if(!d.getElementById('guidedProgressSidebar'))setTimeout(boot,120)}
boot();
})();